[features]
seeds = false
skip-lint = false
[programs.devnet]
switchboard = "Eyx38NvnsWRpQJho1fTzj7BvJB29d4JTJYTrkVUiQ4Ur"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anonymous/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
